name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # windows-latest
        # https://github.com/ZenGo-X/kms-secp256k1/issues/25
        # https://github.com/vhnatyk/gmp-release
        # https://github.com/TonyBogdanov/zip
        os: [macOS-latest, ubuntu-latest]
    environment: Test
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
    - uses: actions/setup-python@v1
    - uses: BSFishy/pip-action@v1
      with:
        packages: |
          maturin
    - name: Build
      run: maturin build --release --manylinux off